version: '3'
services:
  apiservice:
    build: './server'
    image: course-manager-api-image
    container_name: course-manager-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./server:/home/node/app
      - node_modules:/home/node/app/node_modules 
volumes:
  node_modules: